Repository NextCommunity/NextCommunity.github.io, pull requests merged in 2021-06, with the labels that each got.

#8 Create muriturca.md
  _networks/muriturca.md
Labels: good first issue

#10 Add pre-commit
  .editorconfig
  .github/dependabot.yml
  .github/linters/.markdown-lint.yml
  .github/linters/.yaml-lint.yml
  .github/workflows/lint.yml
  .github/workflows/super-linter.yml
  .gitignore
  .pre-commit-config.yaml
  404.md
  CNAME
  CODEOWNERS
  Gemfile.lock
  README.md
  _config.yml
  _layouts/home.html
  _networks/muriturca.md
  _posts/2020-10-01-hello.md
  _posts/2021-06-14-automate-telegram-pyrogram-python.md
  _posts/2021-06-14-static-website-using-github-jeykll.md
  about/index.md
  about/open-source.main
  about/open-source.md
  asset/style.css
  blog.md
  codespell.txt
  index.md
  network.md
  server
  super-linter.report/.keep
Labels: enhancement

#12 Fix spelling and remove _site folder
  README.md
  _site/404.html
  _site/CNAME
  _site/LICENSE
  _site/README.md
  _site/asset/style.css
  _site/blog/automate-telegram-pyrogram-python/index.html
  _site/blog/hello-world/index.html
  _site/blog/index.html
  _site/blog/static-website-using-github-jeykll/index.html
  _site/index.html
  _site/robots.txt
  _site/sitemap.xml
  about/index.md
  index.md
  network.md
Labels: documentation, enhancement

#14 Fix grammar, links and spelling
  _posts/2021-06-14-automate-telegram-program-python.md
  about/index.md
Labels: documentation

#15 Add codespell and prettier as pre-commit
  .pre-commit-config.yaml
  about/index.md
  about/open-source.md
  codespell.txt
Labels: documentation

#16 Update Beast
  Gemfile
  Gemfile.lock
  _config.yml
  _layouts/default.html
  _layouts/home.html
  _networks/jbampton.md
  assets/style.css
Labels: documentation

#17 Add `enimiste` in _networks directory
  _networks/enimiste.md
Labels: documentation

#21 Adding Abdul Majid
  _networks/majidabdulred.md
Labels: documentation, good first issue

#22 Fix name of Nouni Elbachir
  _networks/enimiste.md
Labels: documentation

#23 Create ajakov.md
  _networks/ajakov.md
Labels: documentation, good first issue

#25 create Majalian
  _networks/Majalian
Labels: documentation, good first issue

#26 Fix Majalian
  _networks/majalian.md
Labels: documentation

#29 Create tHe-AK.md
  _networks/tHe-AK.md
Labels: documentation, good first issue

#30 Fix lint
  _networks/tHe-AK.md
Labels: documentation

#38 Anderson
  _networks/Anderson.md
Labels: documentation, good first issue

#39 Fix lint
  _networks/Anderson.md
  _networks/ayush.md
  network.md
Labels: documentation

#41 Lint
  _networks/mahabub.md
Labels: documentation

#42 Remove Jekyll Admin
  Gemfile
  Gemfile.lock
  _config.yml
Labels: dependencies

#44 Fix grammar and spelling
  _networks/victoraraica.md
Labels: documentation

#46 Clean up ra1nbow.md
  _networks/ra1nbow.md
Labels: documentation

#47 Added gakramx card
  _networks/gakramx.md
Labels: documentation

#48 Create abdorah.md
  _networks/abdorah.md
Labels: documentation, good first issue

#49 Lint
  _networks/abdorah.md
  _networks/gakramx.md
Labels: documentation

#50 update abdorah.md profil
  _networks/abdorah.md
Labels: documentation

#52 Fix link and run pre-commit
  _networks/JayantGoel001.md
  _networks/abdorah.md
  index.md
Labels: code style, documentation

#54 Create HunainAnis.md
  _networks/HunainAnis.md
Labels: documentation, good first issue
