Repository NextCommunity/NextCommunity.github.io, pull requests merged in 2022-02, with the labels that each got.

#82 added my account info
  _networks/kenhorlador.md
Labels: good first issue

#83 Run pre-commit and lint
  _networks/SushantAdh07.md
Labels: code style

#86 Use liquid markup for the copyright year
  _includes/footer.html
  _networks/MaxCkett.md
Labels: enhancement, code style

#88 Run pre-commit and lint whitespace
  _networks/NimishKashyap,md
Labels: code style

#89 Rename workflows
  .github/workflows/super-linter.yml
Labels: good first issue

#90 Create Barrerson.md
  _networks/Barrerson.md
Labels: good first issue
