Repository NextCommunity/NextCommunity.github.io, pull requests merged in 2023-05, with the labels that each got.

#124 add rubiin to organization
  _networks/rubiin.md
Labels: good first issue

#125 Added my profile in _networks
  _networks/NimishKashyap.md
  _networks/mohammadshaad.md
Labels: good first issue

#127 Fix alifiroozidev
  _networks/alifiroozidev.md
Labels: bug

#128 Remove about Max
  about/index.md
  about/open-source.main
  about/open-source.md
Labels: good first issue

#129 Clean up network profiles
  _networks/GabrielTheophilo.md
  _networks/HammedBabatunde.md
  _networks/IgbinosaIwinosa.md
Labels: documentation

#130 HTML5 clean up
  _includes/social-metatags.html
  _layouts/default.html
Labels: code style

#131 Further improvements
  404.md
  _config.yml
  index.md
  network.md
Labels: documentation, good first issue

#132 Clean up more - details
  README.md
  index.md
Labels: documentation

#133 Delete super-linter folder
  super-linter.report/.keep
Labels: good first issue

#135 Remove old images
  _config.yml
  demo1.jpg
  demo2.jpg
Labels: good first issue
