Repository NextCommunity/NextCommunity.github.io, pull requests merged in 2024-05, with the labels that each got.

#142 Create anufdo
  _networks/anufdo
Labels: good first issue

#143 Create sbhatm1213.md
  _networks/sbhatm1213.md
Labels: good first issue

#144 Fix anufdo
  _networks/anufdo.md
Labels: bug

#146 Remove 404 users
  _networks/abd-ar.md
  _networks/codingSpecies.md
Labels: good first issue

#148 pre-commit autoupdate
  .gitignore
  .pre-commit-config.yaml
Labels: tests

#149 Restore user new gh profile name
  _networks/iabdr.md
Labels: documentation, good first issue

#152 Gemfile add webrick
  Gemfile
  Gemfile.lock
Labels: bug, good first issue

#153 Fix comma bug with locations
  _layouts/network.md
  network.md
Labels: bug, good first issue

#157 Update lint.yml - remove misspell
  .github/workflows/lint.yml
Labels: good first issue

#160 Update README.md
  README.md
Labels: documentation
