Repository NextCommunity/NextCommunity.github.io, pull requests merged in 2025-04, with the labels that each got.

#199 Run pre-commit; fix lints
  .pre-commit-config.yaml
  _networks/TinotendaMhedziso.md
  _networks/sm4rtdev.md
Labels: code style, tests

#196 Create OrionFable.md
  _networks/OrionFable.md
Labels: good first issue

#200 Update pre-commit hooks
  .pre-commit-config.yaml
  codespell.txt
Labels: dependencies, tests
